// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtrgY6AEyt3-6wl-6NtJBxRaqmBhiLl5M',
    appId: '1:1044532384629:web:bb4799554278e78122793c',
    messagingSenderId: '1044532384629',
    projectId: 'todolistapp-92482',
    authDomain: 'todolistapp-92482.firebaseapp.com',
    storageBucket: 'todolistapp-92482.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO8TRcEEwVljN2OxS9F-yFMmwNmuACTJo',
    appId: '1:1044532384629:android:b717a2b7364ac72d22793c',
    messagingSenderId: '1044532384629',
    projectId: 'todolistapp-92482',
    storageBucket: 'todolistapp-92482.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwzWRrYReUb8GwpzIg7SDClWKkh7AH5TM',
    appId: '1:1044532384629:ios:327dec5d8c538c2d22793c',
    messagingSenderId: '1044532384629',
    projectId: 'todolistapp-92482',
    storageBucket: 'todolistapp-92482.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwzWRrYReUb8GwpzIg7SDClWKkh7AH5TM',
    appId: '1:1044532384629:ios:327dec5d8c538c2d22793c',
    messagingSenderId: '1044532384629',
    projectId: 'todolistapp-92482',
    storageBucket: 'todolistapp-92482.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtrgY6AEyt3-6wl-6NtJBxRaqmBhiLl5M',
    appId: '1:1044532384629:web:c86f23b6d2c64b5422793c',
    messagingSenderId: '1044532384629',
    projectId: 'todolistapp-92482',
    authDomain: 'todolistapp-92482.firebaseapp.com',
    storageBucket: 'todolistapp-92482.appspot.com',
  );
}
